version: "2.20.2"

name: senate-simulation

services:
    database:
        image: mysql:8.0
        ports: 
            - "3307:3306"
        networks:
            - main_net
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-senate_sim}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-change_me}
            MYSQL_USER: ${DB_USERNAME:-your_db_user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-change_me}
        volumes:
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    client:
        build:
            dockerfile: ./Docker/blog-client.Dockerfile
        ports: 
            - "80:80"
        networks:
            - main_net
        volumes:
            - ./src/:/var/www/html/
            - ./.env:/var/www/html/.env:ro
            
networks:
    main_net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: "127.0.0.2"
    
    
        